# -*- coding: utf-8 -*-
"""WorkingWithRequests.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RNaCG62a8eh57y3CqOQa4LmhgEDkY65p
"""

import requests

url = 'https://crawler-test.com'

response = requests.get(url)

print('URL: ', response.url)

print('Status Code: ', response.status_code)

print('Headers: ', response.headers)

"""Simple Post Requests"""

import requests

url = 'https://httpbin.org/post'

payload = {
    'name':'Bamidele',
    'last_name':'Tewogbade ',
    'website':'https://crawler-test.com'
}

r = requests.post(url,data=payload)
r.json()